// source: ChangeDesc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.variflight.dataservice.ChangeDesc', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.ChangeDesc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.variflight.dataservice.ChangeDesc.repeatedFields_, null);
};
goog.inherits(proto.com.variflight.dataservice.ChangeDesc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.ChangeDesc.displayName = 'proto.com.variflight.dataservice.ChangeDesc';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.variflight.dataservice.ChangeDesc.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.ChangeDesc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.ChangeDesc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.ChangeDesc.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldtags: msg.getFieldtags_asB64(),
    changetags: msg.getChangetags_asB64(),
    fieldschangedescsList: jspb.Message.toObjectList(msg.getFieldschangedescsList(),
    proto.com.variflight.dataservice.ChangeDesc.toObject, includeInstance),
    mapInt32Map: (f = msg.getMapInt32Map()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapInt64Map: (f = msg.getMapInt64Map()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapBoolMap: (f = msg.getMapBoolMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapStringMap: (f = msg.getMapStringMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapInt32RemovedMap: (f = msg.getMapInt32RemovedMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapInt64RemovedMap: (f = msg.getMapInt64RemovedMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapBoolRemovedMap: (f = msg.getMapBoolRemovedMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : [],
    mapStringRemovedMap: (f = msg.getMapStringRemovedMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.ChangeDesc.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.ChangeDesc}
 */
proto.com.variflight.dataservice.ChangeDesc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.ChangeDesc;
  return proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.ChangeDesc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.ChangeDesc}
 */
proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFieldtags(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setChangetags(value);
      break;
    case 3:
      var value = new proto.com.variflight.dataservice.ChangeDesc;
      reader.readMessage(value,proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader);
      msg.addFieldschangedescs(value);
      break;
    case 4:
      var value = msg.getMapInt32Map();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 5:
      var value = msg.getMapInt64Map();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt64, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 6:
      var value = msg.getMapBoolMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readBool, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, false, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 7:
      var value = msg.getMapStringMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, "", new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 8:
      var value = msg.getMapInt32RemovedMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 9:
      var value = msg.getMapInt64RemovedMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt64, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 10:
      var value = msg.getMapBoolRemovedMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readBool, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, false, new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    case 11:
      var value = msg.getMapStringRemovedMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.ChangeDesc.deserializeBinaryFromReader, "", new proto.com.variflight.dataservice.ChangeDesc());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.ChangeDesc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldtags_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getChangetags_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getFieldschangedescsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter
    );
  }
  f = message.getMapInt32Map(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapInt64Map(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeInt64, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapBoolMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeBool, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapStringMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapInt32RemovedMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapInt64RemovedMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeInt64, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapBoolRemovedMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeBool, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
  f = message.getMapStringRemovedMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(11, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.ChangeDesc.serializeBinaryToWriter);
  }
};


/**
 * optional bytes fieldTags = 1;
 * @return {!(string|Uint8Array)}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getFieldtags = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes fieldTags = 1;
 * This is a type-conversion wrapper around `getFieldtags()`
 * @return {string}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getFieldtags_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFieldtags()));
};


/**
 * optional bytes fieldTags = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFieldtags()`
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getFieldtags_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFieldtags()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.setFieldtags = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes changeTags = 2;
 * @return {!(string|Uint8Array)}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getChangetags = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes changeTags = 2;
 * This is a type-conversion wrapper around `getChangetags()`
 * @return {string}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getChangetags_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getChangetags()));
};


/**
 * optional bytes changeTags = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChangetags()`
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getChangetags_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getChangetags()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.setChangetags = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * repeated ChangeDesc fieldsChangeDescs = 3;
 * @return {!Array<!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getFieldschangedescsList = function() {
  return /** @type{!Array<!proto.com.variflight.dataservice.ChangeDesc>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.variflight.dataservice.ChangeDesc, 3));
};


/**
 * @param {!Array<!proto.com.variflight.dataservice.ChangeDesc>} value
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
*/
proto.com.variflight.dataservice.ChangeDesc.prototype.setFieldschangedescsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.com.variflight.dataservice.ChangeDesc=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.variflight.dataservice.ChangeDesc}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.addFieldschangedescs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.com.variflight.dataservice.ChangeDesc, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearFieldschangedescsList = function() {
  return this.setFieldschangedescsList([]);
};


/**
 * map<int32, ChangeDesc> map_int32 = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapInt32Map = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapInt32Map = function() {
  this.getMapInt32Map().clear();
  return this;};


/**
 * map<int64, ChangeDesc> map_int64 = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapInt64Map = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapInt64Map = function() {
  this.getMapInt64Map().clear();
  return this;};


/**
 * map<bool, ChangeDesc> map_bool = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<boolean,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapBoolMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<boolean,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapBoolMap = function() {
  this.getMapBoolMap().clear();
  return this;};


/**
 * map<string, ChangeDesc> map_string = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapStringMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapStringMap = function() {
  this.getMapStringMap().clear();
  return this;};


/**
 * map<int32, ChangeDesc> map_int32_removed = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapInt32RemovedMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapInt32RemovedMap = function() {
  this.getMapInt32RemovedMap().clear();
  return this;};


/**
 * map<int64, ChangeDesc> map_int64_removed = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapInt64RemovedMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapInt64RemovedMap = function() {
  this.getMapInt64RemovedMap().clear();
  return this;};


/**
 * map<bool, ChangeDesc> map_bool_removed = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<boolean,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapBoolRemovedMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<boolean,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapBoolRemovedMap = function() {
  this.getMapBoolRemovedMap().clear();
  return this;};


/**
 * map<string, ChangeDesc> map_string_removed = 11;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.variflight.dataservice.ChangeDesc>}
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.getMapStringRemovedMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.variflight.dataservice.ChangeDesc>} */ (
      jspb.Message.getMapField(this, 11, opt_noLazyCreate,
      proto.com.variflight.dataservice.ChangeDesc));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ChangeDesc} returns this
 */
proto.com.variflight.dataservice.ChangeDesc.prototype.clearMapStringRemovedMap = function() {
  this.getMapStringRemovedMap().clear();
  return this;};


goog.object.extend(exports, proto.com.variflight.dataservice);
