// source: Proto.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.com.variflight.dataservice.ProtoDesc', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.ProtoDesc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.variflight.dataservice.ProtoDesc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.ProtoDesc.displayName = 'proto.com.variflight.dataservice.ProtoDesc';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.ProtoDesc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.ProtoDesc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.ProtoDesc.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filesMap: (f = msg.getFilesMap()) ? f.toObject(includeInstance, undefined) : [],
    nocacheprefix: (f = msg.getNocacheprefix()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    fullcacheprefix: (f = msg.getFullcacheprefix()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    incrementcacheprefix: (f = msg.getIncrementcacheprefix()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    defaultttl: (f = msg.getDefaultttl()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    defaultmaxversion: (f = msg.getDefaultmaxversion()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    rpcttlsMap: (f = msg.getRpcttlsMap()) ? f.toObject(includeInstance, undefined) : [],
    rpcmaxversionsMap: (f = msg.getRpcmaxversionsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.ProtoDesc}
 */
proto.com.variflight.dataservice.ProtoDesc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.ProtoDesc;
  return proto.com.variflight.dataservice.ProtoDesc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.ProtoDesc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.ProtoDesc}
 */
proto.com.variflight.dataservice.ProtoDesc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = msg.getFilesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readBytes, null, "", "");
         });
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setNocacheprefix(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setFullcacheprefix(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setIncrementcacheprefix(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setDefaultttl(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setDefaultmaxversion(value);
      break;
    case 8:
      var value = msg.getRpcttlsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    case 9:
      var value = msg.getRpcmaxversionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.ProtoDesc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.ProtoDesc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.ProtoDesc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeBytes);
  }
  f = message.getNocacheprefix();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getFullcacheprefix();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIncrementcacheprefix();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getDefaultttl();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getDefaultmaxversion();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getRpcttlsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
  f = message.getRpcmaxversionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, bytes> files = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!(string|Uint8Array)>}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getFilesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!(string|Uint8Array)>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearFilesMap = function() {
  this.getFilesMap().clear();
  return this;};


/**
 * optional google.protobuf.StringValue NoCachePrefix = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getNocacheprefix = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
*/
proto.com.variflight.dataservice.ProtoDesc.prototype.setNocacheprefix = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearNocacheprefix = function() {
  return this.setNocacheprefix(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.hasNocacheprefix = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue FullCachePrefix = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getFullcacheprefix = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
*/
proto.com.variflight.dataservice.ProtoDesc.prototype.setFullcacheprefix = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearFullcacheprefix = function() {
  return this.setFullcacheprefix(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.hasFullcacheprefix = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue IncrementCachePrefix = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getIncrementcacheprefix = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
*/
proto.com.variflight.dataservice.ProtoDesc.prototype.setIncrementcacheprefix = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearIncrementcacheprefix = function() {
  return this.setIncrementcacheprefix(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.hasIncrementcacheprefix = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int32Value defaultTTL = 6;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getDefaultttl = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 6));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
*/
proto.com.variflight.dataservice.ProtoDesc.prototype.setDefaultttl = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearDefaultttl = function() {
  return this.setDefaultttl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.hasDefaultttl = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Int32Value defaultMaxVersion = 7;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getDefaultmaxversion = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 7));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
*/
proto.com.variflight.dataservice.ProtoDesc.prototype.setDefaultmaxversion = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearDefaultmaxversion = function() {
  return this.setDefaultmaxversion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.hasDefaultmaxversion = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * map<string, int32> rpcTTLs = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getRpcttlsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearRpcttlsMap = function() {
  this.getRpcttlsMap().clear();
  return this;};


/**
 * map<string, int32> rpcMaxVersions = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.getRpcmaxversionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.ProtoDesc} returns this
 */
proto.com.variflight.dataservice.ProtoDesc.prototype.clearRpcmaxversionsMap = function() {
  this.getRpcmaxversionsMap().clear();
  return this;};


goog.object.extend(exports, proto.com.variflight.dataservice);
