// source: TestMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.com.variflight.dataservice.test.StudentScore', null, global);
goog.exportSymbol('proto.com.variflight.dataservice.test.StudentScoresMap', null, global);
goog.exportSymbol('proto.com.variflight.dataservice.test.exam', null, global);
goog.exportSymbol('proto.com.variflight.dataservice.test.student', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.test.student = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.com.variflight.dataservice.test.student.repeatedFields_, null);
};
goog.inherits(proto.com.variflight.dataservice.test.student, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.test.student.displayName = 'proto.com.variflight.dataservice.test.student';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.test.exam = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.variflight.dataservice.test.exam, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.test.exam.displayName = 'proto.com.variflight.dataservice.test.exam';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.test.StudentScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.variflight.dataservice.test.StudentScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.test.StudentScore.displayName = 'proto.com.variflight.dataservice.test.StudentScore';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.variflight.dataservice.test.StudentScoresMap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.variflight.dataservice.test.StudentScoresMap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.variflight.dataservice.test.StudentScoresMap.displayName = 'proto.com.variflight.dataservice.test.StudentScoresMap';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.variflight.dataservice.test.student.repeatedFields_ = [10009,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.test.student.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.test.student.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.test.student} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.student.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    age: jspb.Message.getFieldWithDefault(msg, 3, 0),
    tagsMap: (f = msg.getTagsMap()) ? f.toObject(includeInstance, undefined) : [],
    comment: (f = msg.getComment()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    ivx: (f = msg.getIvx()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    tags2Map: (f = msg.getTags2Map()) ? f.toObject(includeInstance, proto.google.protobuf.Int64Value.toObject) : [],
    s: (f = msg.getS()) && proto.com.variflight.dataservice.test.student.toObject(includeInstance, f),
    msMap: (f = msg.getMsMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.test.student.toObject) : [],
    rsList: jspb.Message.toObjectList(msg.getRsList(),
    proto.com.variflight.dataservice.test.student.toObject, includeInstance),
    riList: jspb.Message.toObjectList(msg.getRiList(),
    google_protobuf_wrappers_pb.Int64Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.test.student}
 */
proto.com.variflight.dataservice.test.student.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.test.student;
  return proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.test.student} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.test.student}
 */
proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAge(value);
      break;
    case 4:
      var value = msg.getTagsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setComment(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setIvx(value);
      break;
    case 7:
      var value = msg.getTags2Map();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Int64Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Int64Value());
         });
      break;
    case 100:
      var value = new proto.com.variflight.dataservice.test.student;
      reader.readMessage(value,proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader);
      msg.setS(value);
      break;
    case 1001:
      var value = msg.getMsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.test.student());
         });
      break;
    case 10009:
      var value = new proto.com.variflight.dataservice.test.student;
      reader.readMessage(value,proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader);
      msg.addRs(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.addRi(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.test.student.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.test.student.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.test.student} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.student.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAge();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTagsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getComment();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIvx();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getTags2Map(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Int64Value.serializeBinaryToWriter);
  }
  f = message.getS();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.com.variflight.dataservice.test.student.serializeBinaryToWriter
    );
  }
  f = message.getMsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1001, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.test.student.serializeBinaryToWriter);
  }
  f = message.getRsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10009,
      f,
      proto.com.variflight.dataservice.test.student.serializeBinaryToWriter
    );
  }
  f = message.getRiList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.com.variflight.dataservice.test.student.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.variflight.dataservice.test.student.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 age = 3;
 * @return {number}
 */
proto.com.variflight.dataservice.test.student.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.setAge = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * map<string, string> tags = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.com.variflight.dataservice.test.student.prototype.getTagsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearTagsMap = function() {
  this.getTagsMap().clear();
  return this;};


/**
 * optional google.protobuf.StringValue comment = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.variflight.dataservice.test.student.prototype.getComment = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
*/
proto.com.variflight.dataservice.test.student.prototype.setComment = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearComment = function() {
  return this.setComment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.test.student.prototype.hasComment = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int32Value ivx = 6;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.com.variflight.dataservice.test.student.prototype.getIvx = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 6));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
*/
proto.com.variflight.dataservice.test.student.prototype.setIvx = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearIvx = function() {
  return this.setIvx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.test.student.prototype.hasIvx = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * map<string, google.protobuf.Int64Value> tags2 = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Int64Value>}
 */
proto.com.variflight.dataservice.test.student.prototype.getTags2Map = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Int64Value>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.google.protobuf.Int64Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearTags2Map = function() {
  this.getTags2Map().clear();
  return this;};


/**
 * optional student s = 100;
 * @return {?proto.com.variflight.dataservice.test.student}
 */
proto.com.variflight.dataservice.test.student.prototype.getS = function() {
  return /** @type{?proto.com.variflight.dataservice.test.student} */ (
    jspb.Message.getWrapperField(this, proto.com.variflight.dataservice.test.student, 100));
};


/**
 * @param {?proto.com.variflight.dataservice.test.student|undefined} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
*/
proto.com.variflight.dataservice.test.student.prototype.setS = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearS = function() {
  return this.setS(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.test.student.prototype.hasS = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * map<int32, student> ms = 1001;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.test.student>}
 */
proto.com.variflight.dataservice.test.student.prototype.getMsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.test.student>} */ (
      jspb.Message.getMapField(this, 1001, opt_noLazyCreate,
      proto.com.variflight.dataservice.test.student));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearMsMap = function() {
  this.getMsMap().clear();
  return this;};


/**
 * repeated student rs = 10009;
 * @return {!Array<!proto.com.variflight.dataservice.test.student>}
 */
proto.com.variflight.dataservice.test.student.prototype.getRsList = function() {
  return /** @type{!Array<!proto.com.variflight.dataservice.test.student>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.variflight.dataservice.test.student, 10009));
};


/**
 * @param {!Array<!proto.com.variflight.dataservice.test.student>} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
*/
proto.com.variflight.dataservice.test.student.prototype.setRsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10009, value);
};


/**
 * @param {!proto.com.variflight.dataservice.test.student=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.variflight.dataservice.test.student}
 */
proto.com.variflight.dataservice.test.student.prototype.addRs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10009, opt_value, proto.com.variflight.dataservice.test.student, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearRsList = function() {
  return this.setRsList([]);
};


/**
 * repeated google.protobuf.Int64Value ri = 10;
 * @return {!Array<!proto.google.protobuf.Int64Value>}
 */
proto.com.variflight.dataservice.test.student.prototype.getRiList = function() {
  return /** @type{!Array<!proto.google.protobuf.Int64Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 10));
};


/**
 * @param {!Array<!proto.google.protobuf.Int64Value>} value
 * @return {!proto.com.variflight.dataservice.test.student} returns this
*/
proto.com.variflight.dataservice.test.student.prototype.setRiList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.google.protobuf.Int64Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Int64Value}
 */
proto.com.variflight.dataservice.test.student.prototype.addRi = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.google.protobuf.Int64Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.variflight.dataservice.test.student} returns this
 */
proto.com.variflight.dataservice.test.student.prototype.clearRiList = function() {
  return this.setRiList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.test.exam.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.test.exam.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.test.exam} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.exam.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cls: jspb.Message.getFieldWithDefault(msg, 2, ""),
    studentid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    score: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.test.exam}
 */
proto.com.variflight.dataservice.test.exam.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.test.exam;
  return proto.com.variflight.dataservice.test.exam.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.test.exam} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.test.exam}
 */
proto.com.variflight.dataservice.test.exam.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCls(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStudentid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.test.exam.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.test.exam.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.test.exam} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.exam.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCls();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStudentid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getScore();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.com.variflight.dataservice.test.exam.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.variflight.dataservice.test.exam} returns this
 */
proto.com.variflight.dataservice.test.exam.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cls = 2;
 * @return {string}
 */
proto.com.variflight.dataservice.test.exam.prototype.getCls = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.variflight.dataservice.test.exam} returns this
 */
proto.com.variflight.dataservice.test.exam.prototype.setCls = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 studentid = 3;
 * @return {number}
 */
proto.com.variflight.dataservice.test.exam.prototype.getStudentid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.variflight.dataservice.test.exam} returns this
 */
proto.com.variflight.dataservice.test.exam.prototype.setStudentid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 score = 4;
 * @return {number}
 */
proto.com.variflight.dataservice.test.exam.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.variflight.dataservice.test.exam} returns this
 */
proto.com.variflight.dataservice.test.exam.prototype.setScore = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.test.StudentScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.test.StudentScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.StudentScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    s: (f = msg.getS()) && proto.com.variflight.dataservice.test.student.toObject(includeInstance, f),
    examsMap: (f = msg.getExamsMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.test.exam.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.test.StudentScore}
 */
proto.com.variflight.dataservice.test.StudentScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.test.StudentScore;
  return proto.com.variflight.dataservice.test.StudentScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.test.StudentScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.test.StudentScore}
 */
proto.com.variflight.dataservice.test.StudentScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.variflight.dataservice.test.student;
      reader.readMessage(value,proto.com.variflight.dataservice.test.student.deserializeBinaryFromReader);
      msg.setS(value);
      break;
    case 2:
      var value = msg.getExamsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.test.exam.deserializeBinaryFromReader, "", new proto.com.variflight.dataservice.test.exam());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.test.StudentScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.test.StudentScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.StudentScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getS();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.variflight.dataservice.test.student.serializeBinaryToWriter
    );
  }
  f = message.getExamsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.test.exam.serializeBinaryToWriter);
  }
};


/**
 * optional student s = 1;
 * @return {?proto.com.variflight.dataservice.test.student}
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.getS = function() {
  return /** @type{?proto.com.variflight.dataservice.test.student} */ (
    jspb.Message.getWrapperField(this, proto.com.variflight.dataservice.test.student, 1));
};


/**
 * @param {?proto.com.variflight.dataservice.test.student|undefined} value
 * @return {!proto.com.variflight.dataservice.test.StudentScore} returns this
*/
proto.com.variflight.dataservice.test.StudentScore.prototype.setS = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.variflight.dataservice.test.StudentScore} returns this
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.clearS = function() {
  return this.setS(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.hasS = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<string, exam> exams = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.variflight.dataservice.test.exam>}
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.getExamsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.variflight.dataservice.test.exam>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.com.variflight.dataservice.test.exam));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.test.StudentScore} returns this
 */
proto.com.variflight.dataservice.test.StudentScore.prototype.clearExamsMap = function() {
  this.getExamsMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.variflight.dataservice.test.StudentScoresMap.prototype.toObject = function(opt_includeInstance) {
  return proto.com.variflight.dataservice.test.StudentScoresMap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.variflight.dataservice.test.StudentScoresMap} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.StudentScoresMap.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsMap: (f = msg.getResultsMap()) ? f.toObject(includeInstance, proto.com.variflight.dataservice.test.StudentScore.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.variflight.dataservice.test.StudentScoresMap}
 */
proto.com.variflight.dataservice.test.StudentScoresMap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.variflight.dataservice.test.StudentScoresMap;
  return proto.com.variflight.dataservice.test.StudentScoresMap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.variflight.dataservice.test.StudentScoresMap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.variflight.dataservice.test.StudentScoresMap}
 */
proto.com.variflight.dataservice.test.StudentScoresMap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getResultsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.com.variflight.dataservice.test.StudentScore.deserializeBinaryFromReader, 0, new proto.com.variflight.dataservice.test.StudentScore());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.variflight.dataservice.test.StudentScoresMap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.variflight.dataservice.test.StudentScoresMap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.variflight.dataservice.test.StudentScoresMap} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.variflight.dataservice.test.StudentScoresMap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.com.variflight.dataservice.test.StudentScore.serializeBinaryToWriter);
  }
};


/**
 * map<int32, StudentScore> results = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.com.variflight.dataservice.test.StudentScore>}
 */
proto.com.variflight.dataservice.test.StudentScoresMap.prototype.getResultsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.com.variflight.dataservice.test.StudentScore>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.com.variflight.dataservice.test.StudentScore));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.variflight.dataservice.test.StudentScoresMap} returns this
 */
proto.com.variflight.dataservice.test.StudentScoresMap.prototype.clearResultsMap = function() {
  this.getResultsMap().clear();
  return this;};


goog.object.extend(exports, proto.com.variflight.dataservice.test);
